
# This file was *autogenerated* from the file my_pruner.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_60 = Integer(60); _sage_const_600 = Integer(600); _sage_const_0p51 = RealNumber('0.51'); _sage_const_1p = RealNumber('1.')
from fpylll import IntegerMatrix, GSO, LLL, Pruning, FPLLL

A = IntegerMatrix.random(_sage_const_60 , "intrel", bits=_sage_const_600 )
_ = LLL.reduction(A)
M = GSO.Mat(A)
_ = M.update_gso()
pr = Pruning.Pruner(M.get_r(_sage_const_0 ,_sage_const_0 ), _sage_const_2 **_sage_const_60 , [M.r()], _sage_const_0p51 )
c = pr.optimize_coefficients([_sage_const_1p  for _ in range(M.d)])
cost, details = pr.single_enum_cost(c, True)
cost

